name: Luma Events extraction

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: Bot Actions

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas PyGithub

      - name: Run script
        env:
          TOKEN: ${{ secrets.CLASSIC_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: python circles.py